name: Publish and deploy

on:
  push:
    branches: master
  release:
    types: [released]

env:
  NODE: 16

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: yarn install, dist and test
        run: |
          yarn install
          yarn run dist
          yarn test
        env:
          CI: true

  deploy:
    # publish only if we are on our own repo
    if: github.repository == 'cozyglow/cozy-glow-theme'

    needs: build # only run if build succeeds

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12 # use the minimum required version
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn run dist
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - run: aws s3 sync ./dist s3://cozyglow-cdn --acl=public-read --storage-class=INTELLIGENT_TIERING
